### ISSUE TITLE
Missing traveller

### ISSUE THREAD

**Issue by astjohn** [Sitata/issue_tracking#1]
TII reports `bob@gmail.com` is missing despite 200 response.

**Comment by astjohn** [comment]
@mattmalinoski - I can confirm that I don't see `bob@gmail.com` in TII's traveller list, but I'm having trouble reproducing this one. 

I used the following:

`POST => https://staging.sitata.com/api/v1/partner/travellers/`

```
{
    "traveller": {
        "first_name": "Bobby Mcbobface",
        "email": "bob@gmail.com"
    }
}
```
which gave me the traveller's json and a `201` response.

Then running 

`GET => https://staging.sitata.com/api/v1/partner/travellers/?since=0`

gave me the list and Bobby was at the top of the list. After all this, I destroyed the record.

Any ideas? Do you still remember what you posted to the server the first time?

**Comment by mattmalinoski** [comment]
Using the company key, I just tried 
{"traveller": {"first_name": "Jimmy", "last_name": "James", "email": "jimmyjames@gmail.com", "home_country": "US", "language": "EN"}}

It returned a 200 and returned a list of travelers, but Jimmy James was not among them. I then tried  GET => https://staging.sitata.com/api/v1/partner/travellers/?since=0  and didn't see him there either.

**Comment by johnmeade** [comment]
We tried to reproduce the issue using various company token (including the TII token) and various sets of parameters (including your exact parameters) but we have not seen the error yet. It sounds like you are getting a list response when you try to create the traveller -- are you by any chance performing a `get` request with traveller parameters? If this is the case, the request is interpretted as "show me the list of travellers" and the traveller json you pass in is ignored.

You must perform 2 requests, one being a `post` to `https://staging.sitata.com/api/v1/partner/travellers` that has the traveller json as the body / params, and the second being a `get` for `https://staging.sitata.com/api/v1/partner/travellers` which returns all the travellers that have been created under your company.

**Comment by mattmalinoski** [comment]
I see what I was doing wrong. I was doing a POST to http instead of https. Once I fixed that it worked.
