### ISSUE TITLE
Sometimes get a bad response syncing a traveler yet the traveler was created. 

### ISSUE THREAD

**Issue by seanflynncontact** [Sitata/issue_tracking#21]
We sometimes get a bad response from Sitata while syncing a traveler. 
Despite that we were able to confirm using postman that the traveler was created.
We only save traveler id and token when the response is success so had to delete the traveler using postman.

**Comment by astjohn** [comment]
From the latest issues, we're deducing that you guys are switching to the `/api/v1/partner/trips` endpoint to create trips and travellers in a single request. If that's the case, you have definitely identified a weakness in this endpoint. i.e. If the trip isn't created, the travellers might still be, and then you won't have the ids of the travellers that were created to recover. Addressing #20 will be the best course of action for your use case / setup.
