### ISSUE TITLE
Unable to search cities

### ISSUE THREAD

**Issue by astjohn** [Sitata/issue_tracking#3]
Sitata's debug API key not working in TII app within Xamarin for searching cities.

**Comment by astjohn** [comment]
@mattmalinoski,

I may have given you the wrong API key at first. It may work now, however, the next release will use the proper iOS Google Places framework. Which essentially means that instead of enabling Google Places Web Services on the Google API Console...  you would enable Google Places iOS. 

This new approach is working on iOS. Whether we can get it working on Xamarin remains to be seen.  :-D

**Comment by astjohn** [comment]
@mattmalinoski,

It's a miracle. Xamarin worked without hassle. We just published 0.9-pre on nuget. Can you please install and give it a whirl? It should show up on nuget in about 10 minutes.

Thanks!

**Comment by mattmalinoski** [comment]
I installed 0.9-pre and it crashes when I launch the city search:

2017-08-15 15:42:47.528 TravelInsuredMobileCustomerAppiOS[94690:3236468] WARNING: Unable to find and load 'GooglePlaces.bundle' for Google Places API for iOS. This may be a sign that you've forgotten to include a resources bundle in your 'Copy Bundle Resources' build phase. As this bundle contains important resources, you may encounter missing images, translations and other incorrect behavior.


I'm running this on VS 2017.

**Comment by mattmalinoski** [comment]
Turns out I needed the Google API key in my info.debug.plist file as well. This is working now.

**Comment by astjohn** [comment]
Perfect! Thanks @mattmalinoski.
