### ISSUE TITLE
Company Update trip not working

### ISSUE THREAD

**Issue by mattmalinoski** [Sitata/issue_tracking#5]
I tried to update trip 5989fdd638d0c3f38a4acc94 with
{"trip": {"start": "2017-08-12" } }
but the date remained unchanged ("2017-08-13").

**Comment by astjohn** [comment]
@mattmalinoski - When you tried to update this trip... did the original trip have any destinations associated with it?

**Comment by mattmalinoski** [comment]
@astjohn - Yes:

    "destinations": [
        {
            "id": "5989ff0438d0c33aac4accdd",
            "departure_date": "2017-08-13",
            "return_date": "2017-08-18",
            "country_id": "4f831e85fe75bd2c230004fe",
            "country_code": "CN",
            "destination_locations": []
        }
    ],

**Comment by astjohn** [comment]
@mattmalinoski - Thanks. This is something that needs to be documented in our API. When `destinations` are present, the trip `start` and `finish` date are calculated based on the destinations' `departure_date` and `return_date`. If there are multiple destinations, it will determine the start and finish date accounting for all the destination dates.
