### ISSUE TITLE
Company Create a trip not working

### ISSUE THREAD

**Issue by mattmalinoski** [Sitata/issue_tracking#6]
I tried to create a trip with the following:
{"trip": {"name": "My trip", "destinations": [{"entry_date": 1504224000, "exit_date": 1504742400, "country_code": "CN", destination_locations: [{"friendly_name": "Hong Kong", latitude: 22.3964, longitude: 114.1095}]}],"traveller_ids": ["596640bf7819cc62be78fd95", "59663fcb7819cc728578fd8b"]}}

but I got a 400.

**Comment by astjohn** [comment]
`destination_locations` needs quotations around it to be valid JSON. This is likely the cause. Can you please add the quotes and try it again?

**Comment by mattmalinoski** [comment]
Did that and also put quotes around "latitude" and "longitude." It worked. The example in the API needs to be updated.

**Comment by astjohn** [comment]
@mattmalinoski  - Noted. Thanks for running through it!
